server:
    port: 443
    ssl:
      enabled: true
      key-store: file:/mnt/efs/sfdc/keystore.p12   # keystore 위치
      key-store-password: yuri # 설정한 비번
      key-store-type: PKCS12
      key-alias: yuri

salesforce:
    clientId: ${SALESFORCE_CLIENT_ID}
    clientSecret: ${SALESFORCE_CLIENT_SECRET}
    redirectUri: ${SALESFORCE_REDIRECT_URI}
    authUrl: ${SALESFORCE_AUTH_URL}
    tokenUrl: ${SALESFORCE_TOKEN_URL}
    myDomain: ${SALESFORCE_MY_DOMAIN}

spring:
    datasource:
        url: ${DB_URL}
        username: ${DB_USERNAME}
        password: ${DB_PASSWORD}
        driver-class-name: org.mariadb.jdbc.Driver

mybatis:
    mapper-locations: classpath:mapper/**/*.xml
    configuration:
        mapUnderscoreToCamelCase: true

logging:
    level:
        com.sfdcupload.mapper.ExcelMapper: OFF